/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Data } from './Data'

export class Editor {
	left?: number
	right?: number
	top?: number
	width?: number
	height?: number
	multiline?: boolean
	labelPosition?: Editor.LabelPositionEnum
	readOnly?: boolean
	defaultValue?: Data
	key?: string

	constructor(json: JSON | any) {
		Object.assign(this as Editor, json)
	}
}

// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace Editor {
	export type LabelPositionEnum = 'Up' | 'Down' | 'Left' | 'Right'
	export const LabelPositionEnum = {
		Up: 'Up' as LabelPositionEnum,
		Down: 'Down' as LabelPositionEnum,
		Left: 'Left' as LabelPositionEnum,
		Right: 'Right' as LabelPositionEnum,
	}
}
